---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web root directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Deploy page d'accueil HTML
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: reload nginx

- name: Deploy config serveur (proxy API)
  template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf
    mode: '0644'
  notify: reload nginx

- name: Start Nginx (no systemd)
  shell: nginx || true
  args:
    executable: /bin/bash
