$ANSIBLE_VAULT;1.1;AES256
38633334626533653862646432323336343066386664653932323232333633626461643362386239
6638373330643536316631663833306566663962333363390a363065633934316232366338356237
31303432313438373836643738306535313162663761376363356435333339656135663836346566
6661653533303962390a363834663764303861326662353337353962313165363434633136363535
30633564323966336134333237303139343165643638356633653434666661323637623762616433
36633439646131343238353331376130396562383765343664653262643839616134393139363330
65376534393231333061663636633566623535616137343963306262373964353930613138633263
34373063633539653463363736353035613163643935623764616663326533333163323138313839
39666666383232636362633935646137636138316365373864356234306537383336336434356332
66303237353936313032306266393033366566636663336334623536646365636330363661623933
39396235376264326634373038636632303637623839316165663235363639333432396139373132
62303162326631353334623863633036346261346534663164353639343139646661363538646461
33363339393034636337353066323238333965313764313966626366663335333333353939653431
33646364666534356361306339633533663636666566643832393036363766373033616131313139
66383331306261383564306434303534393266663935626463343864653535386130623939646635
36613062626137393361623166383738313332613433333435613131623665303835313939643035
33643730623130343034646631386562393430626136663463383535363464326331636662643131
30663532333634356339626636373463313636393737326266386333613462666263636563386635
37353464666639393838383065636238646565313835353062373466323262333032363034313439
32643039356533323837
